version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:862529903840:task-definition/techmart-ecs"
        LoadBalancerInfo:
          ContainerName: "techmart-container"
          ContainerPort: 5000
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: 
              - "subnet-0c778939b2b7820c7" # Replace with your subnet IDs
              - "subnet-0bf5a4789c12f2599"
            SecurityGroups:
              - "sg-01ef4bb4845cb9b17" # Replace with your security group ID
            AssignPublicIp: "ENABLED"

# Hooks:
#   - BeforeInstall:
#       - Location: scripts/stop_application.sh
#         Timeout: 300
#         Runas: root
#   - ApplicationStart:
#       - Location: scripts/start_application.sh
#         Timeout: 300
#         Runas: root
#   - ApplicationStop:
#       - Location: scripts/stop_application.sh
#         Timeout: 300
#         Runas: root
#   - ValidateService:
#       - Location: scripts/validate_service.sh
#         Timeout: 300
#         Runas: root