name: SageMaker Notebook CI/CD PipelineS

on:
  push:
    branches: [ main ]
    paths:
      - 'machine_learning/training.ipynb'
      - 'requirements.txt'
      - 'machine_learning/script/on-start.sh'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install/Update AWS CLI
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y unzip curl
        
        # Download and install/update AWS CLI
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        
        # Check if AWS CLI exists and install/update accordingly
        if command -v aws &> /dev/null; then
          echo "AWS CLI found, updating..."
          sudo ./aws/install --update
        else
          echo "AWS CLI not found, installing..."
          sudo ./aws/install
        fi
        
        # Clean up
        rm -rf awscliv2.zip aws/
        
        aws --version

    - name: Verify AWS Credentials
      run: |
        set -e
        aws sts get-caller-identity
        aws sagemaker list-notebook-instances --max-items 5

    - name: Deploy Lifecycle Configuration
      run: |
        set -e
        SCRIPT_PATH="machine_learning/script/on-start.sh"
        CONFIG_NAME="notebook-config-$(date +%Y%m%d%H%M%S)"

        echo "::group::Find SageMaker Notebook Instance"
        INSTANCE_NAME=$(aws sagemaker list-notebook-instances \
          --status-equals InService \
          --query "NotebookInstances[0].NotebookInstanceName" \
          --output text)
        echo "Notebook Instance: $INSTANCE_NAME"
        echo "::endgroup::"

        if [ -z "$INSTANCE_NAME" ] || [ "$INSTANCE_NAME" = "None" ]; then
          echo "::error::No active SageMaker notebook instance found"
          exit 1
        fi

        # Verify the script exists
        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "::error::Script file $SCRIPT_PATH not found"
          exit 1
        fi

        cp "$SCRIPT_PATH" lifecycle_script.sh
        chmod +x lifecycle_script.sh

        echo "::group::Create Lifecycle Config"
        LIFECYCLE_SCRIPT=$(base64 -w 0 lifecycle_script.sh)
        aws sagemaker create-notebook-instance-lifecycle-config \
          --notebook-instance-lifecycle-config-name "$CONFIG_NAME" \
          --on-start Content="$LIFECYCLE_SCRIPT"
        echo "::endgroup::"

        echo "::group::Attach Lifecycle Config to Notebook"
        aws sagemaker update-notebook-instance \
          --notebook-instance-name "$INSTANCE_NAME" \
          --lifecycle-config-name "$CONFIG_NAME"
        echo "::endgroup::"

        echo "::group::Restart Notebook Instance"
        aws sagemaker stop-notebook-instance --notebook-instance-name "$INSTANCE_NAME"
        
        # Wait for notebook to stop with timeout
        STOP_TIMEOUT=300  # 5 minutes
        ELAPSED=0
        while [ "$(aws sagemaker describe-notebook-instance \
          --notebook-instance-name "$INSTANCE_NAME" \
          --query "NotebookInstanceStatus" --output text)" != "Stopped" ]; do
          if [ $ELAPSED -gt $STOP_TIMEOUT ]; then
            echo "::error::Timeout waiting for notebook to stop"
            exit 1
          fi
          echo "Waiting for notebook to stop... ($ELAPSED seconds)"
          sleep 10
          ELAPSED=$((ELAPSED + 10))
        done

        aws sagemaker start-notebook-instance --notebook-instance-name "$INSTANCE_NAME"
        
        # Wait for notebook to start with timeout
        START_TIMEOUT=300  # 5 minutes
        ELAPSED=0
        while [ "$(aws sagemaker describe-notebook-instance \
          --notebook-instance-name "$INSTANCE_NAME" \
          --query "NotebookInstanceStatus" --output text)" != "InService" ]; do
          if [ $ELAPSED -gt $START_TIMEOUT ]; then
            echo "::error::Timeout waiting for notebook to start"
            exit 1
          fi
          echo "Waiting for notebook to start... ($ELAPSED seconds)"
          sleep 10
          ELAPSED=$((ELAPSED + 10))
        done
        echo "::endgroup::"

        echo "::notice::Notebook instance updated with lifecycle configuration successfully"
        
        # Clean up temporary files
        rm -f lifecycle_script.sh